### ISSUE TITLE
To be Fixed 0517

### ISSUE THREAD

**Issue by seunghwanly** [CSID-DGU/2020-1-OSSP2-SEOULLO-3#7]
- [x] User Tab 에서 firebase에 없는 게시글이 그대로 남아있는 문제

- [x] Comment를 누르면 사용자 프로필이 보이지않는 문제

**Comment by jonghapark** [comment]
> * [x]  User Tab 에서 firebase에 없는 게시글이 그대로 남아있는 문제
* 파이어베이스에서 게시글을 지웠으나 스토리지에서 지우지 않아서 생긴 오류
: 파이어베이스 스토리지 정리로 해결
> * [x]  Comment를 누르면 사용자 프로필이 보이지않는 문제
* CommentLIstAdapter.java 의 이미지로 로드를 Glide로 바꾸어 해결
Commit : 40a9f6b
